

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ReactJs CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x,]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run : rm -rf node_module
    - run : npm install -g npm@latest
    - run : npm install --force
    - name: build
      run: npm run build --if-present
      env:
       CI: false
    - run : mv /var/www/html/TPE_FRONT/_work/TPE_FRONT/TPE_FRONT/build /var/www/html/TPE_API/_work/TPE_API/TPE_API/
    - run : mv /var/www/html/TPE_FRONT/_work/TPE_FRONT/TPE_FRONT/build/static /var/www/html/TPE_API/_work/TPE_API/TPE_API/
